[client]
toolbarMode = "viewer"

[theme]
base = "light"
primaryColor = "#2E4257"
backgroundColor = "#FEFEFD"
secondaryBackgroundColor = "#FEFEFD"
textColor = "#15140F"
font = "sans serif"
baseRadius = "none"
showWidgetBorder = false
